version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./www/html:/var/www/html
        depends_on:
            - php

    php:
        build: ./docker/php
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./www/html:/var/www/html
        depends_on:
            - db
            
    composer:
        image: composer
        volumes:
            - .:/app
        command: install

    db:
        image: postgres:10
        env_file: 
            - ./postgresql.env 
        ports:
            - 5433:5432
        volumes:
            - ./docker/postgres/:/var/lib/postgresql            